version: "3.3"
services:
  # ========================
  # Микросервисы
  # ========================

  auth-service-dev:
    container_name: auth-service-dev
    build:
      context: ./auth-service
      dockerfile: dockerfile
    volumes:
      - ./auth-service/:/usr/src/auth-service
      - /usr/src/auth-service/node_modules
    ports:
      - "3081:1081"
    working_dir: /usr/src/auth-service
    depends_on: 
      - postgres-db-auth-dev
    env_file:
      - ./auth-service/.env.dev
    networks:
      - mynet-dev

  hos-service-dev:
    container_name: hos-service-dev
    build:
      context: ./hos-service
      dockerfile: dockerfile
    volumes:
      - ./hos-service:/usr/src/hos-service
      - /usr/src/hos-service/node_modules
    ports:
      - "3082:1082"
    working_dir: /usr/src/hos-service
    links:
      - mongo-db-dev
    env_file:
      - ./hos-service/.env.dev
    networks:
      - mynet-dev

  animal-service-dev:
    container_name: animal-service-dev
    build:
      context: ./animal-service
      dockerfile: dockerfile
    volumes:
      - ./animal-service:/usr/src/animal-service
      - /usr/src/animal-service/node_modules
    ports:
      - "3083:1083"
    working_dir: /usr/src/animal-service
    links:
      - postgres-db-animal-dev
    env_file:
      - ./animal-service/.env.dev
    networks:
      - mynet-dev

  # ========================
  # Базы данных
  # ========================

  postgres-db-auth-dev:
    container_name: postgres-db-auth-dev
    image: postgres:12.3-alpine
    volumes:
      - auth_pg_data-dev:/var/lib/postgresql/data/auth
    env_file:
      - ./auth-service/.env.dev
    networks:
      - mynet-dev

  postgres-db-animal-dev:
    container_name: postgres-db-animal-dev
    image: postgres:14
    env_file:
      - ./animal-service/.env.dev
    networks:
      - mynet-dev
    volumes:
      - animal_pg_data-dev:/var/lib/postgresql/data/animals

  mongo-db-dev:
    container_name: mongo-db-dev
    image: mongo:6.0
    volumes:
      - ./hos-service/db/:/data/db
    command: mongod --quiet --logpath /dev/null 
    env_file:
      - ./hos-service/.env.dev
    networks:
      - mynet-dev

volumes:
  auth_pg_data-dev:
  animal_pg_data-dev:
networks:
  mynet-dev:
    driver: bridge
    ipam:
      driver: default