version: "3.3"
services:
  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service
      dockerfile: dockerfile
    volumes:
      - ./auth-service/:/usr/src/auth-service
      - /usr/src/auth-service/node_modules
    ports:
      - "1081:1081"
    working_dir: /usr/src/auth-service
    depends_on: 
      - postgres-db
    env_file:
      - ./auth-service/.env
    networks:
      - mynet

  postgres-db:
    container_name: postgres-db
    image: postgres:12.3-alpine
    volumes:
      - postgres-app-data:/data
    ports:
      - "5433:5432"
    env_file:
      - ./auth-service/.env
    networks:
      - mynet

  hos-service:
    container_name: hos-service
    build:
      context: ./hos-service
      dockerfile: dockerfile
    volumes:
      - ./hos-service:/usr/src/hos-service
      - /usr/src/hos-service/node_modules
    ports:
      - "1082:1082"
    working_dir: /usr/src/hos-service
    links:
      - mongo-db
    env_file:
      - ./hos-service/.env
    networks:
      - mynet

  mongo-db:
    container_name: mongo-db
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./hos-service/db/:/data/db
    command: mongod --quiet --logpath /dev/null 
    networks:
      - mynet

volumes:
  postgres-app-data:
networks:
  mynet:
    driver: bridge
    ipam:
      driver: default