services:
  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service
      dockerfile: dockerfile
    volumes:
      - ./auth-service/:/usr/src/auth-service
      - /usr/src/auth-service/node_modules
    ports:
      - "1081:1081"
    working_dir: /usr/src/auth-service
    depends_on: 
      - postgres-db
    env_file:
      - ./auth-service/.env
    networks:
      - mynet

  postgres-db:
    container_name: postgres-db
    image: postgres:12.3-alpine
    volumes:
      - postgres-app-data:/data
    env_file:
      - ./auth-service/.env
    networks:
      - mynet

  hos-service:
    container_name: hos-service
    build:
      context: ./hos-service
      dockerfile: dockerfile
    volumes:
      - ./hos-service:/usr/src/hos-service
      - /usr/src/hos-service/node_modules
    ports:
      - "1082:1082"
    working_dir: /usr/src/hos-service
    links:
      - mongo-db
    env_file:
      - ./hos-service/.env
    networks:
      - mynet

  mongo-db:
    container_name: mongo-db
    image: mongo:6.0
    volumes:
      - ./hos-service/db/:/data/db
    command: mongod --auth --quiet --logpath /dev/null
    env_file:
      - ./hos-service/.env
    networks:
      - mynet
  
  animal-service:
    container_name: animal-service
    build:
      context: ./animal-service
      dockerfile: dockerfile
    volumes:
      - ./animal-service/:/usr/src/animal-service
      - /usr/src/animal-service/node_modules
    ports:
      - "1083:1083"
    working_dir: /usr/src/animal-service
    depends_on: 
      - postgres-db-animal-service
    env_file:
      - ./animal-service/.env
    networks:
      - mynet

  postgres-db-animal-service:
    container_name: postgres-db-animal-service
    image: postgres:14
    environment:
      LANG: en_US.utf8
      LC_ALL: en_US.utf8
      POSTGRES_SHARED_BUFFERS: 64MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 128MB
    volumes:
      - animal-service-volume:/data
    env_file:
      - ./animal-service/.env
    networks:
      - mynet

volumes:
  postgres-app-data:
  animal-service-volume:

networks:
  mynet:
    driver: bridge
    ipam:
      driver: default