version: "3.3"
services:
  all:
    restart: unless-stopped

  # ========================
  # Микросервисы
  # ========================

  auth-service-dev:
    container_name: auth-service-dev
    build:
      context: ./auth-service
      dockerfile: dockerfile
    volumes:
      - ./auth-service/:/usr/src/auth-service
      - /usr/src/auth-service/node_modules
    ports:
      - "3081:1081"
    working_dir: /usr/src/auth-service
    depends_on: 
      - postgres-db-auth-dev
    env_file:
      - ./auth-service/.env.dev
    networks:
      - mynet-dev
    deploy:
      resources:
        limits:
          memory: 100M  # Уменьшить лимит
          cpus: "0.3"

  hos-service-dev:
    container_name: hos-service-dev
    build:
      context: ./hos-service
      dockerfile: dockerfile
    volumes:
      - ./hos-service:/usr/src/hos-service
      - /usr/src/hos-service/node_modules
    ports:
      - "3082:1082"
    working_dir: /usr/src/hos-service
    links:
      - mongo-db-dev
    env_file:
      - ./hos-service/.env.dev
    networks:
      - mynet-dev
    deploy:
      resources:
        limits:
          memory: 100M  # Уменьшить лимит
          cpus: "0.3"

  animal-service-dev:
    container_name: animal-service-dev
    build:
      context: ./animal-service
      dockerfile: dockerfile
    volumes:
      - ./animal-service:/usr/src/animal-service
      - /usr/src/animal-service/node_modules
    ports:
      - "3083:1083"
    working_dir: /usr/src/animal-service
    links:
      - postgres-db-animal-dev
    env_file:
      - ./animal-service/.env.dev
    networks:
      - mynet-dev
    deploy:
      resources:
        limits:
          memory: 100M  # Уменьшить лимит
          cpus: "0.3"

  # ========================
  # Базы данных
  # ========================

  postgres-db-auth-dev:
    container_name: postgres-db-auth-dev
    image: postgres:14
    volumes:
      - auth_pg_data-dev:/var/lib/postgresql/data
    environment:
      LANG: en_US.utf8
      LC_ALL: en_US.utf8
      POSTGRES_SHARED_BUFFERS: 64MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 128MB
    env_file:
      - ./auth-service/.env.dev
    networks:
      - mynet-dev
    deploy:
      resources:
        limits:
          memory: 200M
          cpus: "0.5"

  postgres-db-animal-dev:
    container_name: postgres-db-animal-dev
    image: postgres:14
    environment:
      LANG: en_US.utf8
      LC_ALL: en_US.utf8
      POSTGRES_SHARED_BUFFERS: 64MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 128MB
    env_file:
      - ./animal-service/.env.dev
    networks:
      - mynet-dev
    volumes:
      - animal_pg_data-dev:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 200M
          cpus: "0.5"

  mongo-db-dev:
    container_name: mongo-db-dev
    image: mongo:6.0
    volumes:
      - ./hos-service/db-dev/:/data/db
    command: mongod --quiet --logpath /dev/null --nojournal --wiredTigerCacheSizeGB 0.25 --syncdelay 600
    env_file:
      - ./hos-service/.env.dev
    networks:
      - mynet-dev
    deploy:
      resources:
        limits:
          memory: 300M  # Ограничить кэш
          cpus: "1.0"

volumes:
  auth_pg_data-dev:
  animal_pg_data-dev:
networks:
  mynet-dev:
    driver: bridge
    ipam:
      driver: default