version: "3.3"
services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: dockerfile
    volumes:
      - ./:/usr/src/auth-service
      - /usr/src/auth-service/node_modules
    ports:
      - "1081:1081"
  hos-service:
    build:
      context: ./hos-service
      dockerfile: dockerfile
    volumes:
      - ./:/usr/src/hos-service
      - /usr/src/hos-service/node_modules
    ports:
      - "1082:1082"