name: CI-CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        #port: ${{ secrets.SSH_PORT }}
        script: |
          cd /home/hos-microservices-composer/auth-service
          git pull origin master
          cd /home/hos-microservices-composer/hos-service
          git pull origin master
          cd /home/hos-microservices-composer
          docker-compose up --build