name: Production V2 Deployment

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST_V2 }}
        username: ${{ secrets.SSH_USERNAME_V2 }}
        key: ${{ secrets.SSH_KEY_V2 }}
        script: |
          cd ${{ secrets.REPO_PATH }}
      
          docker compose stop auth-service hos-service animal-service
          docker compose rm -f auth-service hos-service animal-service

          git pull origin master
          cd auth-service && git checkout master && git pull origin master && cd ..
          cd hos-service && git checkout master && git pull origin master && cd ..
          cd animal-service && git checkout master && git pull origin master && cd ..

          docker compose up --build -d auth-service
          sleep 30
          docker compose up --build -d hos-service
          sleep 30
          docker compose up --build -d animal-service